Trait {
	#name : #MolForcesServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolRobot
}

{ #category : #services }
MolForcesServices >> getAngularForce [
	"Get and return the angular force of the left/right mouvement."
]

{ #category : #services }
MolForcesServices >> getLinearForce [
	"Get and return the linear force of the forward/backward mouvement."
]
